name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this solve? Why would this be useful?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of SimplyTerm does this relate to?
      options:
        - Terminal / Connection
        - Vault / Security
        - SFTP Browser
        - Plugin System
        - UI / UX
        - Settings
        - Port Forwarding
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any mockups, screenshots, or references that help explain the idea.
